### ISSUE TITLE
Chunks don't include the entire parent hierarchy when forming locators

### ISSUE THREAD

**Issue by jonathanmcbride** [ApplauseAuto/core-java-framework-dist#1]
It appears from testing that a new chunk subsumes the parent's locator, but not the parent's ABSOLUTE locator.

Consider a situation such as this:
```
<ul class="top">
   <li> <ul class="middle">
      <li class="bottom">...</li> //<!------ what I get />
      <li class="bottom">...</li>
   </ul></li>
   <li> <ul class="middle">
      <li class="bottom">...</li>
      <li class="bottom">...</li>
   </ul></li>
</ul>

<ul class="top">
   <li> <ul class="middle">
      <li class="bottom">...</li> //<!------ what I want />
      <li class="bottom">...</li>
   </ul></li>
   <li> <ul class="middle">
      <li class="bottom">...</li>
      <li class="bottom">...</li>
   </ul></li>
</ul>
```

And this automation code:
```
Chunk secondTop = new Chunk(thePage,".top :nth(1)");
Chunk middle = new Chunk(top, ".middle :nth(0)");
Chunk bottom = new Chunk(middle, ".bottom :nth(0)");
```

Expected: the `bottom` chunk's locator to be `.top :nth(1) .middle :nth(0) .bottom :nth(0)`.
Actual: the `bottom` chunk's locator is `.middle :nth(0) .bottom :nth(0)`.

This causes me to select and operate on the wrong element.

**Comment by kodayashi** [comment]
Hi @jonathanmcbride, I'm not sure we've had many (or any) cases where we're nesting chunks like this, so it may not have been taken into account when put together.

@brianmrock - Is the expected behavior in line with what you'd expect to see? If so, can we get this bug on the product roadmap for 1.6.x?

**Comment by brianmrock** [comment]
This will require a pretty invasive change to support nested chunks.  It hasn't been a common use case, but for 1.7 I will look into doing chunk.getElement() intead for nested chunks. 

Moving this to Jira.

**Comment by brianmrock** [comment]
https://appauto.atlassian.net/browse/COR-146
