### ISSUE TITLE
logger logs twice

### ISSUE THREAD

**Issue by jonathanmcbride** [ApplauseAuto/core-java-framework-dist#2]
Any time I use the logger, I get the same line printed twice in my output.

**Comment by kodayashi** [comment]
Hi @jonathanmcbride,

What version of core are you on? Also, what do your log4j-debug.properties and log4j.properties files look like?

**Comment by jonathanmcbride** [comment]
1.5.36

log4j:
```
log4j.rootLogger=info,ca
log4j.logger.com.amazonaws=error
log4j.logger.com.applause=info


# CA Buffer Appender
log4j.appender.ca=org.apache.log4j.ConsoleAppender
log4j.appender.ca.layout=org.apache.log4j.EnhancedPatternLayout
log4j.appender.ca.layout.ConversionPattern=%d{yyyyMMdd-HH\:mm\:ss.SSS}{GMT} - %m%n
```

Debug:
```
log4j.rootLogger=info,ca
log4j.logger.com.amazonaws=error
log4j.logger.com.applause=debug


# CA Buffer Appender
log4j.appender.ca=org.apache.log4j.ConsoleAppender
log4j.appender.ca.layout=org.apache.log4j.EnhancedPatternLayout
log4j.appender.ca.layout.ConversionPattern=%d{yyyyMMdd-HH\:mm\:ss.SSS}{GMT} - %m%n
```

The decompiled LogController class looks like it's using and printing to both a log4j logger AND a testnglogger - which could explain the duplication.

**Comment by kodayashi** [comment]
Thanks @jonathanmcbride, I'll tag this as needing some investigation and rope in engineering.

**Comment by brianmrock** [comment]
It does report out to two, but only logfj output should be coming to the screen,  sounds like you may have a class that created a Log4J logger rather then a LogController.  Can you check your source?  I can not recreate this bug in our template projects.

**Comment by jonathanmcbride** [comment]
My original statement was wrong, it's not every message that gets duplicated. INFOs work as expected, WARNs (and higher?) double output.

Example:
```
20170324-19:52:41.356 - disco-prerelease-tests-651 : Did not find expected doucment count, returning 31
[DiscoText] [WARN] disco-prerelease-tests-651 : Did not find expected doucment count, returning 31
```

**Comment by jonathanmcbride** [comment]
We wrote a custom logger, so we can close this.
